apiVersion: v1
data:
  enable-vts-status: "false"
  proxy-read-timeout: "86400"
  proxy-send-timeout: "86400"
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.13.1
    component: controller
    heritage: Tiller
    release: jetti
  name: jetti-nginx-ingress-controller
  namespace: default
