apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jetti
  labels:
    app: jetti
spec:
  template:
    metadata:
      labels:
        app: jetti
        tier: web
    spec:
      containers:
      - name: jetti
        image: eu.gcr.io/jetti-pg/jetti-fs-mat:latest
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jetti
  annotations:
    kubernetes.io/ingress.global-static-ip-name: jetti-ip
  labels:
    app: jetti
spec:
  backend:
    serviceName: jetti-api
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jetti-api
  labels:
    app: jetti
spec:
  type: NodePort
  selector:
    app: jetti
    tier: web
  ports:
  - port: 8080
    targetPort: 8080


#kubectl apply -f cube.yaml
#docker build --rm -f Dockerfile -t jetti-fs-mat:latest .
#docker tag jetti-fs-mat eu.gcr.io/jetti-pg/jetti-fs-mat
#gcloud docker -- push eu.gcr.io/jetti-pg/jetti-fs-mat

#docker tag jetti-fs-mat jetti.azurecr.io/jetti-fs-mat
#docker push jetti.azurecr.io/jetti-fs-mat