#cat jetti.key | base64
#cat jetti.pem | base64
#gcloud kubectl apply -f add-secret-ssl.yaml

apiVersion: v1
kind: Secret
metadata:
  name: jetti-ssl
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt:
  tls.key:


apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: jetti-ssl
    namespace: default
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUd0akNDQlo2Z0F3SUJBZ0lKQUlTWHlCakVSYmNLTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUcwTVFzd0NRWUQKVlFRR0V3SlZVekVRTUE0R0ExVUVDQk1IUVhKcGVtOXVZVEVUTUJFR0ExVUVCeE1LVTJOdmRI
UnpaR0ZzWlRFYQpNQmdHQTFVRUNoTVJSMjlFWVdSa2VTNWpiMjBzSUVsdVl5NHhMVEFyQmdOVkJBc1RKR2gwZEhBNkx5OWpaWEowCmN5NW5iMlJoWkdSNUxtTnZiUzl5WlhCdmMybDBiM0o1THpFek1ERUdBMVVFQXhNcVIyOGdSR0ZrWkhrZ1UyVmoKZFhKbElFTmxjblJwWm1
sallYUmxJRUYxZEdodmNtbDBlU0F0SUVjeU1CNFhEVEU0TVRJek1ESXhNekF6TTFvWApEVEl3TVRJeU9ERTJNRFV3TWxvd1BURWhNQjhHQTFVRUN4TVlSRzl0WVdsdUlFTnZiblJ5YjJ3Z1ZtRnNhV1JoCmRHVmtNUmd3RmdZRFZRUUREQThxTG1wbGRIUnBMV0Z3Y0M1amIyMH
dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRQzNzUG16L29Rc3YzODlTczZmYnhuQXJGWC9QS2xmZzRTMFVpZmFsY29iNVpPOQpyWXRZbWw5YldHRnBRTjlid1ZaOS9pUUtwWXhLeDZtd1YzYmF0T1VXbzQzY2sxK2FTeWtNa0JoSXhWUDk5ckNSC
no2em00V3FvbnpnR3d4YXFFWHNmV1c0eDZBajZsWlowYWtmeU5ZSEFsVnFva1hIR0RDTWI1aHdXaGRpZ28yQ0UKOTJROCtGMmw1ZWYxYVUrVUlqdU5vT204Q0VGV01oNHVkS05qY1o5eG9OR0tvQnhwY1B6ZGhkVlJvdDZrOXRhWQphS0tqOEI3ZTdlem45VWZsa0VaZExjbUk1
UW1EaEgxTkZ1Z1NVZS9pUHNaRnN2LzNPV2VIOXcvZmxDcDc1TmtsCmR6b2x4SERDY3YvVkFRM2lIVUhucGxleEZONzdYU2h3d1JXSGd5MjNBZ01CQUFHamdnTS9NSUlET3pBTUJnTlYKSFJNQkFmOEVBakFBTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlF
jREFqQU9CZ05WSFE4QgpBZjhFQkFNQ0JhQXdOd1lEVlIwZkJEQXdMakFzb0NxZ0tJWW1hSFIwY0RvdkwyTnliQzVuYjJSaFpHUjVMbU52CmJTOW5aR2xuTW5NeExUa3dNaTVqY213d1hRWURWUjBnQkZZd1ZEQklCZ3RnaGtnQmh2MXRBUWNYQVRBNU1EY0cKQ0NzR0FRVUZCd0
lCRml0b2RIUndPaTh2WTJWeWRHbG1hV05oZEdWekxtZHZaR0ZrWkhrdVkyOXRMM0psY0c5egphWFJ2Y25rdk1BZ0dCbWVCREFFQ0FUQjJCZ2dyQmdFRkJRY0JBUVJxTUdnd0pBWUlLd1lCQlFVSE1BR0dHR2gwCmRIQTZMeTl2WTNOd0xtZHZaR0ZrWkhrdVkyOXRMekJBQmdnc
kJnRUZCUWN3QW9ZMGFIUjBjRG92TDJObGNuUnAKWm1sallYUmxjeTVuYjJSaFpHUjVMbU52YlM5eVpYQnZjMmwwYjNKNUwyZGthV2N5TG1OeWREQWZCZ05WSFNNRQpHREFXZ0JSQXdyMG5qc3cwZ3pDaU05ZjdiTFB3dEN5QXpqQXBCZ05WSFJFRUlqQWdnZzhxTG1wbGRIUnBM
V0Z3CmNDNWpiMjJDRFdwbGRIUnBMV0Z3Y0M1amIyMHdIUVlEVlIwT0JCWUVGTVlyNzZDcSsyNE5XTzJsd2NiVkI2NEUKM2tpQ01JSUJmd1lLS3dZQkJBSFdlUUlFQWdTQ0FXOEVnZ0ZyQVdrQWRnQ2t1UW1RdEJoWUZJZTdFNkxNWjNBSwpQRFdZQlBrYjM3ampkODBPeUEzY0V
BQUFBV2dCQm85cUFBQUVBd0JITUVVQ0lRRFpJeUJEUUU1YU5EU3lNeUJWClExUVRsREkrVkMzakJYWllQMytyYTJpM1ZRSWdLcDRsMlNhbmRTa3pKNklJa0VhOXVyR2N0cXMwMjFOTjU0RFQKR09TNHFSZ0Fkd0R1UzcyM2RjNWd1dUZDYVIrcjRaNW1vdzkrWDdCeTJJTUF4SH
VKZXFqOXl3QUFBV2dCQnBNZApBQUFFQXdCSU1FWUNJUUNtampXaHhBcldLbGY4aUcvWVdQTitqcHQwejVBb1NPVFR5SFRrVklFWWJ3SWhBSWFkCmtSSWlmY0RzVWRDdHRLK3pNSitsNmhjMGo0ZVJObU8xMDNoZm9iQjRBSFlBWHFkeitkOVd3T2UxTmtoOTBFbmcKTW5xUm1ne
UVvUklTaEJoMWxvRnhSVmdBQUFGb0FRYVgzZ0FBQkFNQVJ6QkZBaUJxbHRGcDZDSTcrSnltWlhDbApMRndNQmF6T1p1akU0NEhORVVaL3YzR3VsUUloQVBUTFhQSW54eVMyNUhRcUlhemIyTmF6ak5MbFcyS09QOXM4Ck13R1U0MlhqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElC
QVFCa1krenFuSVE4M0NkOTVoQy9EY3dxL2ZzRkZiQ24KUStuVDFDRlBLRjk5MjN5dWJkMGhPNG9JLzlZV1B2MHBvdVRtUjRQSjBvSXptK1l6Z1BSRmRlWmFBWWlucnhOeQpKWU0rWnRQQ1NabzErSXUrQThVUWFsWmMwMnZyQS9iejllSkVYMW5mek5sNTZySXAwV0tPcVhjQ3J
xNW9pNk01CnpnNEs5Mlo5YTlrdFl4UVY1emRXYk55UnF2eVdrV2Zwb285bHlRaDJvWDM2dHdUMFJiU0E5SVcyejNkMjlnM28KZmo4NHFvWEF5YjhUeDEyU3BwVHlPWGVLUWRtOVFtaFduVDdWcEI1ODhXaXFqUDBMVXVhQ21UdzZueGdjMWV6WgpGWkVmd2hKY3Z4S0h2S2pMR3
huSWVwQ29TNm1HUlBZVUFMa05Qci9QdTQybHI5V0FDa0xPVlM5SwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tIA==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQzNzUG16L29Rc3YzODkKU3M2ZmJ4bkFyRlgvUEtsZmc0UzBVaWZhbGNvYjVaTzlyWXRZbWw5YldHRnBRTjlid1ZaOS9p
UUtwWXhLeDZtdwpWM2JhdE9VV280M2NrMSthU3lrTWtCaEl4VlA5OXJDUno2em00V3FvbnpnR3d4YXFFWHNmV1c0eDZBajZsWlowCmFrZnlOWUhBbFZxb2tYSEdEQ01iNWh3V2hkaWdvMkNFOTJROCtGMmw1ZWYxYVUrVUlqdU5vT204Q0VGV01oNHUKZEtOamNaOXhvTkdLb0J
4cGNQemRoZFZSb3Q2azl0YVlhS0tqOEI3ZTdlem45VWZsa0VaZExjbUk1UW1EaEgxTgpGdWdTVWUvaVBzWkZzdi8zT1dlSDl3L2ZsQ3A3NU5rbGR6b2x4SERDY3YvVkFRM2lIVUhucGxleEZONzdYU2h3CndSV0hneTIzQWdNQkFBRUNnZ0VCQUpLUDBBdi9MUEtQTURSMU5Yc2
NLQTRFOHZDZE0vNlRieFI0NEhlVlFCY1cKQzlVeFhKY3JSSjRiWEUyZ2h4WXNvcGdRYUMxZWZSdEZSMno5dkVVd1JBRFdLbUF0N2YrcnJHcnJwWlNhYlRPYQoyckxjWW5Zc3NPOHRhb1Jxci9DdDFmRGpaL3JGeWpRMW1qLzBkTWNhVGhhY2xDTWZPUW50c1MyWFloM09XVk9BC
jdVV1kvNVk3MFdrODVkNURudWRMWUZLU1ZuaVRiVVQ5bHlKaCtYWmEvK3AzRVZ5YU5BTVVnTEt4Nk9OdFVENWoKd3NXc3ZlK0ZYSFovSEV0OUdNakZmTGdvbXdITjlCREQ3NW51OUNqRm9GRHlTZEhGdjdYRGl3T3FXcTVLZUFTUQo4a0tsT3BxMVBSZWhRbUdWVURyRVJySlc4
MU05aXEwWndWc3pvZDV5R0pFQ2dZRUE0SnZpRkhpVHNGbjhzY0hpCnpzS3ZsZ01aUVBDdFJDRTFldGlQcDgzQmtiRHVOSzAyTEZZSlVKb1ZucHdwWms1NlV2M1NlNTdkZXVkT2p5SEgKQlNrNFRURkNMSjgwTklKOHZQYVNWVTlYNW9DYUk0RU54NnpzNHRsdWFQOENjZkhsbUZ
5Sk14UU9TMUUzSW5iUgozKzBVVE4zYW1zeXdOMHQwYVdJckYwM3ZuWFVDZ1lFQTBWMGhuNkY2d2pUREl3T1JvK2dWbzN3em40bHdjWEM5CmoyM3Y1Q3ZvU1FZSllHSldFVmRZazA4SFR5SGJLL2NZM0J6Ry9wdmJOZXUzMU4yazdGRHdWNUxYdGZlb21SWUYKK2kxaGYrQUUvUE
YvWUE3YmprTXNuNWZEQWY2RUZHaDNVcUNJU1kzWmVhSzFkTUs4TlVWa1NSc0FWdllTamFYMQpkcHJKUnFTUEhQc0NnWUFDeSs0VXN5dWpsbnMrKzFzSG1BVDNxVEkzVE1mYmdVNVpLVGtncmI4clFUaTJEeklOCmUwVENiQ2k0d05rREhSY0kwWUE5YWN6NEtza2ZueHdMUkdnZ
kRlMzFBRVoySU9uTXNJVkI2cXI5Zzd4bmxNUEgKS0xBS1l3cXM0Ly96eXo5QWxtWmU3SEVCSHhIQXJCb1EzN0xSQWpJbW0wWFdhbW9ZcGRCRGlnVGh3UUtCZ1FDWQpNeWNOWUJ2WThQaG5ET0lra01TaVM5bFBnbCt1NkRHMkFrcmh5aFdjZUhuNmlxSmRDdTJHY1c0ejFiMzZV
VERPClcxRkNxTlVNZHViMkpZY09rS3lZVFZUcG9UZjh5aWpnUFh0aXRkMktjSm1Ub0ZsMksxbFdUOEpoUWNDTkFZQzEKSGFUV0svdk1WRCtydVNHUGJIbkNONUhncGhUSXlyd09VK284bzhheVh3S0JnUURQVHMwN2FyWkZoMTVPUzhoYQp5ZjMyR3RMWU9xdVplWVFCdDR3anJ
zeHFYWWU0SEFQSURxNE9ySm9ncmJydDVMcUxheUJrR2JqRjZXOHFFVWFFCnRoQUdVZVBkUit6aU9kSW0vZG4zS3ZZdlNkNmNVVFFteFhjVDRJaU1GOVU5WmIwdy9xZk5DUzQvOFU0V1RnbisKS2VWVXcxVjJvTUh1MzYrVWR3S3Q5ck44RUE9PQotLS0tLUVORCBQUklWQVRFIE
tFWS0tLS0t
