import locale from '@angular/common/locales/ru';
import { NgModule } from '@angular/core';
import { MessageService } from 'primeng/components/common/messageservice';
import { NgDragDropModule } from 'ng-drag-drop';
import {
    AccordionModule,
    AutoCompleteModule,
    BlockUIModule,
    BreadcrumbModule,
    ButtonModule,
    CalendarModule,
    CheckboxModule,
    ConfirmationService,
    ConfirmDialogModule,
    ContextMenuModule,
    DataTableModule,
    DialogModule,
    DropdownModule,
    FieldsetModule,
    GrowlModule,
    InplaceModule,
    InputMaskModule,
    InputTextareaModule,
    InputTextModule,
    MenuModule,
    MessageModule,
    MessagesModule,
    MultiSelectModule,
    PaginatorModule,
    PanelMenuModule,
    PanelModule,
    PasswordModule,
    ProgressBarModule,
    ProgressSpinnerModule,
    SelectButtonModule,
    SharedModule,
    SpinnerModule,
    SplitButtonModule,
    TabMenuModule,
    TabViewModule,
    TieredMenuModule,
    ToggleButtonModule,
    ToolbarModule,
    TooltipModule,
    TreeTableModule,
    TriStateCheckboxModule,
} from 'primeng/primeng';

import { TableModule } from './common/datatable/table';

@NgModule({
  exports: [
    SharedModule,
    DataTableModule,
    AutoCompleteModule,
    CalendarModule,
    ButtonModule,
    SplitButtonModule,
    SpinnerModule,
    ConfirmDialogModule,
    DialogModule,
    // SidebarModule,
    TooltipModule,
    AccordionModule,
    FieldsetModule,
    TabViewModule,
    MessagesModule,
    MessageModule,
    GrowlModule,
    TreeTableModule,
    CheckboxModule,
    SelectButtonModule,
    InputTextModule,
    // ChipsModule,
    DropdownModule,
    InputTextareaModule,
    InputMaskModule,
    PasswordModule,
    ToggleButtonModule,
    TriStateCheckboxModule,
    // RadioButtonModule,
    PaginatorModule,
    ToolbarModule,
    PanelModule,
    MenuModule,
    ContextMenuModule,
    PanelMenuModule,
    TabMenuModule,
    // MegaMenuModule,
    // SlideMenuModule,
    BreadcrumbModule,
    TieredMenuModule,
    // StepsModule,
    // DragDropModule,
    ProgressBarModule,
    ProgressSpinnerModule,
    MultiSelectModule,
    InplaceModule,
    BlockUIModule,
    TableModule,
    NgDragDropModule
  ],
    providers: [ConfirmationService, MessageService]
})
export class PrimeNGModule { }

export const calendarLocale = {
  firstDayOfWeek: 1,
  dayNames: locale[3][2],
  dayNamesShort: locale[3][0],
  dayNamesMin: locale[3][0],
  monthNames: locale[5][2],
  monthNamesShort: locale[5][1],
  today: 'Today',
  clear: 'Clear'
};

export const dateFormat = 'dd.mm.yy';
