import { NgModule } from '@angular/core';
import {
    AutoCompleteModule,
    ButtonModule,
    CalendarModule,
    ConfirmDialogModule,
    DataTableModule,
    SharedModule,
    FieldsetModule,
    TooltipModule,
    SidebarModule,
    DialogModule,
    AccordionModule,
    TabViewModule,
    MessagesModule,
    MessageModule,
    GrowlModule,
    TreeTableModule,
    TreeModule,
    SplitButtonModule,
    SpinnerModule,
    CheckboxModule,
    InputTextModule,
    SelectButtonModule,
    ToggleButtonModule,
    PasswordModule,
    InputMaskModule,
    InputTextareaModule,
    DropdownModule,
    ChipsModule,
    TriStateCheckboxModule,
    RadioButtonModule,
    ToolbarModule,
    PaginatorModule,
    PanelModule,
    PanelMenuModule,
    ContextMenuModule,
    MenuModule,
    TabMenuModule,
    MegaMenuModule,
    BreadcrumbModule,
    SlideMenuModule,
    TieredMenuModule,
    StepsModule,
    DragDropModule,
    ProgressBarModule,
    ProgressSpinnerModule,
    InplaceModule,
    ConfirmationService,
    MultiSelectModule,
    BlockUIModule
} from 'primeng/primeng';
import { MessageService } from 'primeng/components/common/messageservice';

@NgModule({
  exports: [
    SharedModule,
    DataTableModule,
    AutoCompleteModule,
    CalendarModule,
    ButtonModule,
    SplitButtonModule,
    SpinnerModule,
    ConfirmDialogModule,
    DialogModule,
    SidebarModule,
    TooltipModule,
    AccordionModule,
    FieldsetModule,
    TabViewModule,
    MessagesModule,
    MessageModule,
    GrowlModule,
    TreeTableModule,
    TreeModule,
    CheckboxModule,
    SelectButtonModule,
    InputTextModule,
    ChipsModule,
    DropdownModule,
    InputTextareaModule,
    InputMaskModule,
    PasswordModule,
    ToggleButtonModule,
    TriStateCheckboxModule,
    RadioButtonModule,
    PaginatorModule,
    ToolbarModule,
    PanelModule,
    MenuModule,
    ContextMenuModule,
    PanelMenuModule,
    TabMenuModule,
    MegaMenuModule,
    SlideMenuModule,
    BreadcrumbModule,
    TieredMenuModule,
    StepsModule,
    DragDropModule,
    ProgressBarModule,
    ProgressSpinnerModule,
    MultiSelectModule,
    InplaceModule,
    BlockUIModule
  ],
  providers: [ConfirmationService, MessageService]
})
export class PrimeNGModule { }

import locale from '@angular/common/locales/ru';

export const calendarLocale = {
  firstDayOfWeek: 1,
  dayNames: locale[3][2],
  dayNamesShort: locale[3][0],
  dayNamesMin: locale[3][0],
  monthNames: locale[5][2],
  monthNamesShort: locale[5][1],
  today: 'Today',
  clear: 'Clear'
};

export const dateFormat = 'dd.mm.yy';
